
import type { Employee, TrainingRequest, ApprovalAction } from './types';

const threeMonthsAgo = new Date();
threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);

export const mockEmployees: Employee[] = [
  {
    id: 'emp1',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    department: 'Engineering',
    role: 'employee',
    avatarUrl: 'https://placehold.co/100x100.png',
    managerId: 'sup1', 
    position: 'Software Engineer II',
    staffNo: 'E00123',
    academicQualification: 'B.Sc. Computer Science',
    dateJoined: new Date('2020-06-15'),
    passwordLastChanged: threeMonthsAgo,
    prefersEmailNotifications: true,
    prefersInAppNotifications: true,
  },
  {
    id: 'emp2',
    name: 'Bob Smith',
    email: 'bob@example.com',
    department: 'Marketing',
    role: 'employee',
    avatarUrl: 'https://placehold.co/100x100.png',
    managerId: 'sup2', 
    position: 'Marketing Specialist',
    staffNo: 'E00456',
    academicQualification: 'B.A. Marketing',
    dateJoined: new Date('2021-01-20'),
    passwordLastChanged: new Date('2024-01-10'),
    prefersEmailNotifications: true,
    prefersInAppNotifications: false,
  },
  {
    id: 'sup1',
    name: 'Carol White', 
    email: 'carol@example.com',
    department: 'Engineering',
    role: 'supervisor',
    avatarUrl: 'https://placehold.co/100x100.png',
    position: 'Engineering Manager',
    staffNo: 'S00789',
    academicQualification: 'M.Sc. Software Engineering',
    dateJoined: new Date('2015-03-01'),
    passwordLastChanged: new Date('2023-12-01'),
    prefersEmailNotifications: true,
    prefersInAppNotifications: true,
  },
  {
    id: 'sup2',
    name: 'David Brown', 
    email: 'david@example.com',
    department: 'Marketing',
    role: 'supervisor',
    avatarUrl: 'https://placehold.co/100x100.png',
    position: 'Marketing Director',
    staffNo: 'S00101',
    academicQualification: 'MBA',
    dateJoined: new Date('2018-09-10'),
    passwordLastChanged: threeMonthsAgo,
    prefersEmailNotifications: false,
    prefersInAppNotifications: true,
  },
  {
    id: 'emp3',
    name: 'Eve Davis',
    email: 'eve@example.com',
    department: 'Engineering',
    role: 'employee',
    avatarUrl: 'https://placehold.co/100x100.png',
    managerId: 'sup1', 
    position: 'QA Engineer',
    staffNo: 'E00112',
    academicQualification: 'B.Eng. Electrical Engineering',
    dateJoined: new Date('2022-07-01'),
    passwordLastChanged: new Date('2024-02-15'),
    prefersEmailNotifications: true,
    prefersInAppNotifications: true,
  },
  {
    id: 'thr1',
    name: 'Tom Harris',
    email: 'tom@example.com',
    department: 'Human Resources',
    role: 'thr',
    avatarUrl: 'https://placehold.co/100x100.png',
    position: 'THR Manager',
    staffNo: 'THR001',
    academicQualification: 'MHRM',
    dateJoined: new Date('2019-05-10'),
    passwordLastChanged: new Date('2023-11-20'),
    prefersEmailNotifications: true,
    prefersInAppNotifications: true,
  },
  {
    id: 'ceo1',
    name: 'Grace Lee',
    email: 'grace@example.com',
    department: 'Executive',
    role: 'ceo',
    avatarUrl: 'https://placehold.co/100x100.png',
    position: 'CEO',
    staffNo: 'CEO001',
    academicQualification: 'Ph.D. Business Administration',
    dateJoined: new Date('2010-01-01'),
    passwordLastChanged: new Date('2024-03-01'),
    prefersEmailNotifications: true,
    prefersInAppNotifications: true,
  },
   {
    id: 'cm1',
    name: 'Charles Miller',
    email: 'charles@example.com',
    department: 'Capability Management', // Updated department for clarity
    role: 'cm',
    avatarUrl: 'https://placehold.co/100x100.png',
    position: 'Capability Manager',
    staffNo: 'CM001',
    academicQualification: 'MBA, PMP',
    dateJoined: new Date('2017-11-15'),
    passwordLastChanged: new Date('2024-01-01'),
    prefersEmailNotifications: false,
    prefersInAppNotifications: false,
  },
];

export const mockTrainingRequests: TrainingRequest[] = [];
