
import type { Employee, TrainingRequest, ApprovalAction } from './types';

const threeMonthsAgo = new Date();
threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);

export const mockEmployees: Employee[] = [
  {
    id: 'emp1',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    department: 'Engineering',
    role: 'employee',
    avatarUrl: 'https://placehold.co/100x100.png',
    managerId: 'sup1', 
    position: 'Software Engineer II',
    staffNo: 'E00123',
    academicQualification: 'B.Sc. Computer Science',
    dateJoined: new Date('2020-06-15'),
    passwordLastChanged: threeMonthsAgo,
    prefersEmailNotifications: true,
    prefersInAppNotifications: true,
  },
  {
    id: 'emp2',
    name: 'Bob Smith',
    email: 'bob@example.com',
    department: 'Marketing',
    role: 'employee',
    avatarUrl: 'https://placehold.co/100x100.png',
    managerId: 'sup2', 
    position: 'Marketing Specialist',
    staffNo: 'E00456',
    academicQualification: 'B.A. Marketing',
    dateJoined: new Date('2021-01-20'),
    passwordLastChanged: new Date('2024-01-10'),
    prefersEmailNotifications: true,
    prefersInAppNotifications: false,
  },
  {
    id: 'sup1',
    name: 'Carol White', 
    email: 'carol@example.com',
    department: 'Engineering',
    role: 'supervisor',
    avatarUrl: 'https://placehold.co/100x100.png',
    position: 'Engineering Manager',
    staffNo: 'S00789',
    academicQualification: 'M.Sc. Software Engineering',
    dateJoined: new Date('2015-03-01'),
    passwordLastChanged: new Date('2023-12-01'),
    prefersEmailNotifications: true,
    prefersInAppNotifications: true,
  },
  {
    id: 'sup2',
    name: 'David Brown', 
    email: 'david@example.com',
    department: 'Marketing',
    role: 'supervisor',
    avatarUrl: 'https://placehold.co/100x100.png',
    position: 'Marketing Director',
    staffNo: 'S00101',
    academicQualification: 'MBA',
    dateJoined: new Date('2018-09-10'),
    passwordLastChanged: threeMonthsAgo,
    prefersEmailNotifications: false,
    prefersInAppNotifications: true,
  },
  {
    id: 'emp3',
    name: 'Eve Davis',
    email: 'eve@example.com',
    department: 'Engineering',
    role: 'employee',
    avatarUrl: 'https://placehold.co/100x100.png',
    managerId: 'sup1', 
    position: 'QA Engineer',
    staffNo: 'E00112',
    academicQualification: 'B.Eng. Electrical Engineering',
    dateJoined: new Date('2022-07-01'),
    passwordLastChanged: new Date('2024-02-15'),
    prefersEmailNotifications: true,
    prefersInAppNotifications: true,
  },
  {
    id: 'thr1',
    name: 'Tom Harris',
    email: 'tom@example.com',
    department: 'Human Resources',
    role: 'thr',
    avatarUrl: 'https://placehold.co/100x100.png',
    position: 'THR Manager',
    staffNo: 'THR001',
    academicQualification: 'MHRM',
    dateJoined: new Date('2019-05-10'),
    passwordLastChanged: new Date('2023-11-20'),
    prefersEmailNotifications: true,
    prefersInAppNotifications: true,
  },
  {
    id: 'ceo1',
    name: 'Grace Lee',
    email: 'grace@example.com',
    department: 'Executive',
    role: 'ceo',
    avatarUrl: 'https://placehold.co/100x100.png',
    position: 'CEO',
    staffNo: 'CEO001',
    academicQualification: 'Ph.D. Business Administration',
    dateJoined: new Date('2010-01-01'),
    passwordLastChanged: new Date('2024-03-01'),
    prefersEmailNotifications: true,
    prefersInAppNotifications: true,
  },
   {
    id: 'cm1',
    name: 'Charles Miller',
    email: 'charles@example.com',
    department: 'Contracts',
    role: 'cm',
    avatarUrl: 'https://placehold.co/100x100.png',
    position: 'Contract Manager',
    staffNo: 'CM001',
    academicQualification: 'LLB',
    dateJoined: new Date('2017-11-15'),
    passwordLastChanged: new Date('2024-01-01'),
    prefersEmailNotifications: false,
    prefersInAppNotifications: false,
  },
];

export const mockTrainingRequests: TrainingRequest[] = [
  {
    id: 'req1',
    employeeId: 'emp1', 
    employeeName: 'Alice Johnson',
    trainingTitle: 'Advanced Next.js Workshop',
    justification: 'To improve frontend skills and learn new SSR techniques for upcoming Project Phoenix.',
    organiser: 'TechSeminars Inc.',
    venue: 'Online Platform X',
    startDate: new Date('2024-09-15'),
    endDate: new Date('2024-09-17'),
    cost: 1200,
    mode: 'online',
    programType: 'specialized',
    previousRelevantTraining: 'React Fundamentals (2023)',
    supportingDocuments: [{ name: 'Workshop Brochure.pdf' }],
    status: 'pending',
    currentApprovalStep: 'supervisor',
    approvalChain: [],
    submittedDate: new Date('2024-07-01'),
    lastUpdated: new Date('2024-07-01'),
  },
  {
    id: 'req2',
    employeeId: 'emp2', 
    employeeName: 'Bob Smith',
    trainingTitle: 'Digital Marketing Conference 2024',
    justification: 'To learn about latest trends and network with industry professionals, benefiting our new product launch campaign.',
    organiser: 'Global Marketers Association',
    venue: 'New York City, USA', 
    startDate: new Date('2024-10-05'),
    endDate: new Date('2024-10-07'),
    cost: 2500, 
    mode: 'overseas',
    programType: 'conference/seminar/forum',
    status: 'approved',
    currentApprovalStep: 'completed',
    approvalChain: [
      { stepRole: 'supervisor', decision: 'approved', userId: 'sup2', userName: 'David Brown', notes: 'Looks valuable.', date: new Date('2024-06-16') },
      { stepRole: 'thr', decision: 'approved', userId: 'thr1', userName: 'Tom Harris', notes: 'THR approved.', date: new Date('2024-06-18') },
      { stepRole: 'ceo', decision: 'approved', userId: 'ceo1', userName: 'Grace Lee', notes: 'CEO final approval.', date: new Date('2024-06-20') }
    ],
    submittedDate: new Date('2024-06-15'),
    lastUpdated: new Date('2024-06-20'),
  },
  {
    id: 'req3',
    employeeId: 'emp1', 
    employeeName: 'Alice Johnson',
    trainingTitle: 'Project Management Certification Course',
    justification: 'To enhance leadership and organizational skills for a potential team lead role.',
    organiser: 'PMI Institute',
    venue: 'Local Training Center Alpha',
    startDate: new Date('2024-11-01'),
    endDate: new Date('2024-11-30'),
    cost: 1800,
    mode: 'local',
    programType: 'course',
    status: 'rejected',
    currentApprovalStep: 'completed',
    approvalChain: [
      { stepRole: 'supervisor', decision: 'rejected', userId: 'sup1', userName: 'Carol White', notes: 'Rejected due to budget constraints for this quarter. Please resubmit next quarter.', date: new Date('2024-05-25') }
    ],
    submittedDate: new Date('2024-05-20'),
    lastUpdated: new Date('2024-05-25'),
  },
  {
    id: 'req4',
    employeeId: 'emp3', 
    employeeName: 'Eve Davis',
    trainingTitle: 'Cloud Security Fundamentals',
    justification: 'Essential for understanding security protocols for our cloud migration project.',
    organiser: 'SecureCloud Academy',
    venue: 'Online - AWS Portal',
    startDate: new Date('2024-09-20'),
    endDate: new Date('2024-09-22'),
    cost: 700,
    mode: 'online',
    programType: 'specialized',
    status: 'pending',
    currentApprovalStep: 'thr', 
    approvalChain: [
      { stepRole: 'supervisor', decision: 'approved', userId: 'sup1', userName: 'Carol White', notes: 'Good initiative.', date: new Date('2024-07-12') }
    ],
    submittedDate: new Date('2024-07-10'),
    lastUpdated: new Date('2024-07-12'),
  },
  {
    id: 'req5',
    employeeId: 'emp1', 
    employeeName: 'Alice Johnson',
    trainingTitle: 'Advanced AI Summit',
    justification: 'Crucial for upcoming AI projects.',
    organiser: 'AI Global',
    venue: 'London, UK', 
    startDate: new Date('2024-12-01'),
    endDate: new Date('2024-12-03'),
    cost: 3500, 
    mode: 'overseas',
    programType: 'conference/seminar/forum',
    status: 'pending',
    currentApprovalStep: 'ceo', 
    approvalChain: [
      { stepRole: 'supervisor', decision: 'approved', userId: 'sup1', userName: 'Carol White', notes: 'Seems important.', date: new Date('2024-07-15') },
      { stepRole: 'thr', decision: 'approved', userId: 'thr1', userName: 'Tom Harris', notes: 'THR supports this.', date: new Date('2024-07-17') }
    ],
    submittedDate: new Date('2024-07-14'),
    lastUpdated: new Date('2024-07-17'),
  },
  {
    id: 'req6',
    employeeId: 'emp2',
    employeeName: 'Bob Smith',
    trainingTitle: 'In-House Leadership Workshop',
    justification: 'To prepare for team leadership responsibilities.',
    organiser: 'L1A Internal Training Dept.',
    venue: 'Company HQ - Training Room 3',
    startDate: new Date('2024-08-05'),
    endDate: new Date('2024-08-07'),
    cost: 300, // Low cost, in-house
    mode: 'in-house',
    programType: 'leadership',
    status: 'pending',
    currentApprovalStep: 'supervisor',
    approvalChain: [],
    submittedDate: new Date('2024-07-18'),
    lastUpdated: new Date('2024-07-18'),
  },
];
