import type { Employee, TrainingRequest } from './types';

export const mockEmployees: Employee[] = [
  {
    id: 'emp1',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    department: 'Engineering',
    role: 'employee',
    avatarUrl: 'https://placehold.co/100x100.png',
    managerId: 'sup1',
  },
  {
    id: 'emp2',
    name: 'Bob Smith',
    email: 'bob@example.com',
    department: 'Marketing',
    role: 'employee',
    avatarUrl: 'https://placehold.co/100x100.png',
    managerId: 'sup2',
  },
  {
    id: 'sup1',
    name: 'Carol White',
    email: 'carol@example.com',
    department: 'Engineering',
    role: 'supervisor',
    avatarUrl: 'https://placehold.co/100x100.png',
  },
  {
    id: 'sup2',
    name: 'David Brown',
    email: 'david@example.com',
    department: 'Marketing',
    role: 'supervisor',
    avatarUrl: 'https://placehold.co/100x100.png',
  },
  {
    id: 'emp3',
    name: 'Eve Davis',
    email: 'eve@example.com',
    department: 'Engineering',
    role: 'employee',
    avatarUrl: 'https://placehold.co/100x100.png',
    managerId: 'sup1',
  },
];

export const mockTrainingRequests: TrainingRequest[] = [
  {
    id: 'req1',
    employeeId: 'emp1',
    employeeName: 'Alice Johnson',
    purpose: 'Advanced Next.js Workshop for improving frontend skills and learning new SSR techniques.',
    startDate: new Date('2024-09-15'),
    endDate: new Date('2024-09-17'),
    cost: 1200,
    mode: 'online',
    supportingDocuments: [{ name: 'Workshop Brochure.pdf' }],
    status: 'pending',
    submittedDate: new Date('2024-07-01'),
    lastUpdated: new Date('2024-07-01'),
  },
  {
    id: 'req2',
    employeeId: 'emp2',
    employeeName: 'Bob Smith',
    purpose: 'Digital Marketing Conference 2024 to learn about latest trends and network with industry professionals.',
    startDate: new Date('2024-10-05'),
    endDate: new Date('2024-10-07'),
    cost: 850,
    mode: 'conference',
    status: 'approved',
    submittedDate: new Date('2024-06-15'),
    supervisorNotes: 'Approved. Looks like a valuable conference.',
    lastUpdated: new Date('2024-06-20'),
  },
  {
    id: 'req3',
    employeeId: 'emp1',
    employeeName: 'Alice Johnson',
    purpose: 'Project Management Certification Course to enhance leadership and organizational skills.',
    startDate: new Date('2024-11-01'),
    endDate: new Date('2024-11-30'),
    cost: 2500,
    mode: 'in-person',
    status: 'rejected',
    submittedDate: new Date('2024-05-20'),
    supervisorNotes: 'Rejected due to budget constraints for this quarter. Please resubmit next quarter.',
    lastUpdated: new Date('2024-05-25'),
  },
  {
    id: 'req4',
    employeeId: 'emp3',
    employeeName: 'Eve Davis',
    purpose: 'Cloud Security Fundamentals training.',
    startDate: new Date('2024-09-20'),
    endDate: new Date('2024-09-22'),
    cost: 700,
    mode: 'online',
    status: 'pending',
    submittedDate: new Date('2024-07-10'),
    lastUpdated: new Date('2024-07-10'),
  },
];
